import { bootstrapApplication } from '@angular/platform-browser';
import { RouteReuseStrategy, provideRouter, withPreloading, PreloadAllModules } from '@angular/router';
import { IonicRouteStrategy, provideIonicAngular } from '@ionic/angular/standalone';
import { provideHttpClient } from '@angular/common/http';
import { addIcons } from 'ionicons';
import { 
  heart, 
  heartOutline,
  search, 
  searchOutline,
  home, 
  menu,
  arrowBack,
  warning,
  refresh,
  colorPalette,
  statsChart,
  grid,
  barChart,
  settings,
  informationCircle,
  download,
  list,
  trash,
  star,
  add,
  close,
  play,
  power,
  powerOutline,
  globeOutline,
  pulseOutline,
  radioOutline,
  server,
  library,
  resize,
  apps,
  trophy,
  checkmarkCircle,
  alertCircle,
  share,
  logoIonic,
  logoAngular,
  codeSlash,
  phonePortrait,
  sync,
  logoGithub,
  logoLinkedin,
  personCircle,
  calendar,
  person,
  business,
  mail,
  open,
  // Ícones dos tipos Pokémon
  shield,
  ellipse,
  flame,
  water,
  flash,
  leaf,
  snow,
  fitness,
  skull,
  planet,
  paperPlane,
  eye,
  bug,
  square,
  moon
} from 'ionicons/icons';

import { routes } from './app/app.routes';
import { AppComponent } from './app/app.component';

// Registrar todos os ícones usados na aplicação
addIcons({
  heart,
  'heart-outline': heartOutline,
  search,
  'search-outline': searchOutline,
  home,
  menu,
  'arrow-back': arrowBack,
  warning,
  refresh,
  'color-palette': colorPalette,
  'stats-chart': statsChart,
  grid,
  'bar-chart': barChart,
  settings,
  'information-circle': informationCircle,
  download,
  list,
  trash,
  star,
  add,
  close,
  play,
  power,
  'power-outline': powerOutline,
  'globe-outline': globeOutline,
  'pulse-outline': pulseOutline,
  'radio-outline': radioOutline,
  server,
  library,
  resize,
  apps,
  trophy,
  'checkmark-circle': checkmarkCircle,
  'alert-circle': alertCircle,
  share,
  'logo-ionic': logoIonic,
  'logo-angular': logoAngular,
  'code-slash': codeSlash,
  'phone-portrait': phonePortrait,
  sync,
  'logo-github': logoGithub,
  'logo-linkedin': logoLinkedin,
  'person-circle': personCircle,
  calendar,
  person,
  business,
  mail,
  open,
  // Ícones dos tipos Pokémon
  shield,
  ellipse,
  flame,
  water,
  flash,
  leaf,
  snow,
  fitness,
  skull,
  planet,
  'paper-plane': paperPlane,
  eye,
  bug,
  square,
  moon
});

bootstrapApplication(AppComponent, {
  providers: [
    { provide: RouteReuseStrategy, useClass: IonicRouteStrategy },
    provideIonicAngular(),
    provideRouter(routes, withPreloading(PreloadAllModules)),
    provideHttpClient(),
  ],
});
