// This file is required by karma.conf.js and loads recursively all the .spec and framework files

import 'zone.js/testing';
import { getTestBed } from '@angular/core/testing';
import {
  BrowserDynamicTestingModule,
  platformBrowserDynamicTesting
} from '@angular/platform-browser-dynamic/testing';

// Configurar ícones para testes
import { addIcons } from 'ionicons';
import { 
  heart, 
  heartOutline, 
  home, 
  search, 
  star, 
  list, 
  statsChart,
  arrowBack,
  refresh,
  add,
  remove,
  settings,
  filter,
  close,
  checkmark,
  shield,
  colorPalette,
  download,
  play,
  power,
  powerOutline,
  trash,
  globeOutline,
  pulseOutline,
  radioOutline,
  library,
  resize,
  apps,
  trophy,
  searchOutline,
  warning,
  grid,
  barChart,
  informationCircle,
  ellipse,
  flame,
  water,
  flash,
  leaf,
  snow,
  fitness,
  skull,
  planet,
  paperPlane,
  eye,
  bug,
  square,
  moon
} from 'ionicons/icons';

// Adicionar ícones necessários para os testes
addIcons({
  heart,
  'heart-outline': heartOutline,
  home,
  search,
  star,
  list,
  'stats-chart': statsChart,
  'arrow-back': arrowBack,
  refresh,
  add,
  remove,
  settings,
  filter,
  close,
  checkmark,
  shield,
  'color-palette': colorPalette,
  download,
  play,
  power,
  'power-outline': powerOutline,
  trash,
  'globe-outline': globeOutline,
  'pulse-outline': pulseOutline,
  'radio-outline': radioOutline,
  library,
  resize,
  apps,
  trophy,
  'search-outline': searchOutline,
  warning,
  grid,
  'bar-chart': barChart,
  'information-circle': informationCircle,
  ellipse,
  flame,
  water,
  flash,
  leaf,
  snow,
  fitness,
  skull,
  planet,
  'paper-plane': paperPlane,
  eye,
  bug,
  square,
  moon
});

// First, initialize the Angular testing environment.
getTestBed().initTestEnvironment(
  BrowserDynamicTestingModule,
  platformBrowserDynamicTesting(),
);
